### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by MrKev312** [solidDoWant/Planetbase#1]
Is this project dead?

**Comment by solidDoWant** [comment]
I haven't worked on it in a few months but I occasionally work on the framework and the mod loader, as well as watch for issues on GitHub

**Comment by MrKev312** [comment]
so when's the modding guide coming out? I've tried writing a simple mod based on the code of other mods and it worked but i still don't really know what i'm doing and for instance i wanted to make a starch maker that converts vegetables to starch in the biodome but i cant find how to do that

**Comment by solidDoWant** [comment]
Most of the documentation is currently here: https://github.com/solidDoWant/Planetbase-Framework/wiki/Creating-mods

Additionally I've spent the last 3 evenings working on finishing a complete rewrite of the patcher and framework, as well as writing the mod you mentioned, with documentation, as an example on how to use it.

https://steamcommunity.com/sharedfiles/filedetails/?id=1761162946
https://steamcommunity.com/sharedfiles/filedetails/?id=1761162904
https://steamcommunity.com/sharedfiles/filedetails/?id=1761162877
https://steamcommunity.com/sharedfiles/filedetails/?id=1761162841

I should have all the changes released within a few days.

**Comment by solidDoWant** [comment]
Just released the update as well as the mod you mentioned. Please see below for details:
https://github.com/solidDoWant/Planetbase-Modpatcher/releases/latest
https://github.com/solidDoWant/Planetbase-Framework/releases/latest
https://github.com/solidDoWant/Planetbase-VegetableConverter/releases/latest

Let me know if you have any questions.
